version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - 5672:5672
      - 8085:15672
    volumes:
      - ./.docker/rabbitmq:/var/lib/rabbitmq

  redis:
    image: docker.io/redis/redis-stack:7.2.0-v6
    container_name: redis
    volumes:
      - ./.docker/redis:/data
    ports:
      - 6379:6379
      - 8011:8001

  postgres:
    image: docker.io/postgis/postgis:15-3.3
    container_name: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: trace
      POSTGRES_PASSWORD: trace
      POSTGRES_DB: trace
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  scylla:
    image: scylladb/scylla:5.4
    container_name: scylla
    ports:
      - 9042:9042
      - 9160:9160
    volumes:
      - ./.docker/scylla:/var/lib/scylla
