version: '3.7'

services:
  config:
    image: hyness/spring-cloud-config-server:4.0
    container_name: config
    environment:
      SPRING_PROFILES_ACTIVE: native
    volumes:
    - ./config/default:/config
    - ./config/native-files:/native-files
    ports:
      - 8888:8888

  spring-boot-admin:
    image: slydeveloper/spring-boot-admin
    container_name: spring-boot-admin
    environment:
      SPRING_BOOT_ADMIN_TITLE: Trace
      SPRING_BOOT_ADMIN_USER_NAME: trace
      SPRING_BOOT_ADMIN_USER_PASSWORD: trace
      SPRING_BOOT_ADMIN_SECURITY_ENABLED: 'false'
    ports:
      - 1111:1111
    network_mode: host

  consul:
    image: hashicorp/consul:1.15
    container_name: consul
    ports:
      - 8500:8500

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - 5672:5672
      - 8085:15672
    volumes:
      - ./.docker/rabbitmq:/var/lib/rabbitmq

  redis:
    image: docker.io/redis/redis-stack:6.2.6-v6
    container_name: redis
    volumes:
      - ./.docker/redis:/data
    ports:
      - 6379:6379
      - 8011:8001

  postgres:
    image: docker.io/postgis/postgis:15-3.3
    container_name: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: trace
      POSTGRES_PASSWORD: trace
      POSTGRES_DB: trace
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  scylla:
    image: scylladb/scylla:5.1
    container_name: scylla
    ports:
      - 9042:9042
      - 9160:9160
    volumes:
      - ./.docker/scylla:/var/lib/scylla

  zipkin:
    image: openzipkin/zipkin:2
    container_name: zipkin
    ports:
      - 9411:9411
