version: '3.9'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1

volumes:
  messaging:
  cache:
  db:
  scylladb:
  traccar:

services:
  messaging:
    image: rabbitmq:3-management-alpine
    container_name: messaging
    hostname: messaging
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 8085:15672
    volumes:
      - messaging:/var/lib/rabbitmq
    networks:
      default:
        ipv4_address: 192.168.55.10

  cache:
    image: docker.io/redis/redis-stack:7.2.0-v6
    container_name: cache
    hostname: cache
    restart: unless-stopped
    volumes:
      - cache:/data
    ports:
      - 6379:6379
      - 8011:8001
    networks:
      default:
        ipv4_address: 192.168.55.20

  db:
    image: docker.io/postgis/postgis:15-3.3
    container_name: db
    hostname: db
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trace
      POSTGRES_DB: trace
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      default:
        ipv4_address: 192.168.55.30

  scylladb:
    image: scylladb/scylla:5.4
    container_name: scylladb
    hostname: scylladb
    restart: unless-stopped
    ports:
      - 9042:9042
      - 9160:9160
    volumes:
      - scylladb:/var/lib/scylla
    networks:
      default:
        ipv4_address: 192.168.55.40

  traccar:
    image: ghcr.io/drolx/track:alpine
    container_name: traccar
    restart: unless-stopped
    hostname: traccar
    ports:
      - 6000:5000
      - 6055:5055
      - 8088:8082
    volumes:
      - traccar:/opt/traccar/data:rw
      - ./config/traccar.xml:/opt/traccar/conf/traccar.xml:ro
      - ./logs/:/opt/traccar/logs:rw
    networks:
      default:
        ipv4_address: 192.168.55.50
