---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-core
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: service-core
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: service-core
    spec:
      containers:
      - name: service-core
        image: ghcr.io/ghcr.io/drolx/trace-service-core:0.0.1-preview.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: service-core-env
      terminationGracePeriodSeconds: 180